version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=AnApple123
      - POSTGRES_USER=root
    volumes: 
      - BillSpliterData:/var/lib/postgresql/data
  web:
    build: backend
    restart: always
    depends_on:
      - db
  nginx: 
    build: .
    restart: always
    ports:
      - 80:80
volumes: 
  BillSpliterData: